postgres:
  restart: no
  build: ./postgres
  volumes_from:
    - data
  ports:
    - "5432:5432"
  env_file: .env
 
data:
  restart: no
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

rabbitmq:
  restart: no
  image: rabbitmq
  ports:
     - "5672:5672"

redis:
  restart: no
  image: redis
  ports:
     - "6379:6379"

nginx:
  restart: no
  build: ./nginx/
  volumes:
    - /var/www/static:/var/www/static
  ports:
    - "80:80"
  links:
    - web:web
 
web:
  restart: no
  build: ./web
  expose:
    - "8000"
  volumes:
    - /var/www/static:/usr/src/app/static
    - ./web:/usr/src/app
  links:
    - postgres:postgres 
  env_file: .env
